### ISSUE TITLE
subSR Album undefined at index.js:113

### ISSUE THREAD

**Issue by JanGross** [JanGross/drome-compare#2]
```
drome-compare-1  | /app/src/index.js:113
drome-compare-1  |     if(subSR.album) result = Array.isArray(subSR.album) ? subSR.album : [subSR.album];
drome-compare-1  |              ^
drome-compare-1  |
drome-compare-1  | TypeError: Cannot read properties of undefined (reading 'album')
drome-compare-1  |     at searchAndMatch (/app/src/index.js:113:14)
drome-compare-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
drome-compare-1  |     at async /app/src/index.js:169:29
```

**Comment by JanGross** [comment]
Credentials were outdated.  
We should implement better error messages
